<p>Turns out I'm an idiot :)  The file that was being "created" was saving to invalid path and swallowing the exception, so I thought it was being "created" ok.  When I tried to to instantiate a new FileInputStream, however, it complained that file didn't exist (rightly so).  I had a brainfart and assumed that the java.io.File object actually contained file information in it somewhere.  But as erickson pointed out, that was false.</p>

<p>Thanks Ralph for the code, I used it after I solved the invalid pathing issue.</p>

<p>My code:</p>

<pre><code>ZipOutputStream out = new ZipOutputStream(response.getOutputStream());
byte[] buf = new byte[1024];

File file;
InputStream in;
// Loop through entities
for (TitleProductAccountApproval tpAccountApproval : tpAccountApprovals) {
    // Generate the file    
    file = xmlManager.getXML(
        tpAccountApproval.getTitleProduct().getTitleProductId(), 
        tpAccountApproval.getAccount().getAccountId(), 
        username);

    // Write to zip file
    in = new FileInputStream(file);
    out.putNextEntry(new ZipEntry(file.getName()));

    int len;
    while ((len = in.read(buf)) &gt; 0) {
        out.write(buf, 0, len);
    }

    out.closeEntry();
    in.close();
}

out.close();
</code></pre>
